from pathlib import Path
p=Path(__file__).resolve().parent
s=(p/'template.html').read_text()
css='''
.module-nav{display:flex;gap:8px;margin:0 0 24px;overflow-x:auto}.module-nav button{padding:14px 24px;white-space:nowrap;flex:1;font-size:14px;border-radius:0;border-bottom:2px solid var(--line)}.module-nav b{margin-right:12px;color:#95a597;font-weight:400}.module-nav button.selected{border-color:var(--green)}.frame-icon{width:15px;height:45px}.view-tag{color:var(--green)}
.compare-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px}.compare-column{text-align:center;background:#eceee6;border:1px solid var(--line);border-radius:12px;padding:22px 16px}.compare-column h2{font-size:20px;color:var(--ink);margin:0}.compare-column p{font-size:12px;color:var(--muted);margin:3px 0 18px}.compare-pair{display:grid;grid-template-columns:1fr 1fr;gap:8px}.compare-item{border:0;border-radius:8px;background:#f8f7f0;padding:8px;width:100%}.compare-item img{display:block;height:340px;width:100%;object-fit:contain}.compare-item span{display:block;padding:8px;font-size:12px}.compare-hint{color:var(--muted);font-size:12px;margin-top:16px}.install-steps{display:grid;grid-template-columns:1fr 1fr;gap:7px}.install-steps button{font-size:12px;padding:10px 4px}.install-copy{min-height:116px;margin:17px 0}.install-copy h3{font-size:17px;margin:0 0 9px}.install-copy p{font-size:13px;color:var(--muted);margin:0}.install-actions{display:flex;gap:6px;flex-wrap:wrap}.install-actions button{flex:1;font-size:12px;padding:6px}#play-install{flex-basis:100%}.node-svg{width:100%;height:210px;background:#eeeee6;border-radius:8px;margin:18px 0 0}.node-label{font-size:11px;color:var(--muted);margin:4px 0}.gallery{margin-top:52px;border-top:1px solid var(--line);padding-top:28px}.gallery-title{display:flex;align-items:center;justify-content:space-between;gap:12px}.gallery-title h2{font-size:20px;color:var(--ink);letter-spacing:0}.gallery-title a{color:var(--ink);font-size:12px}.poster-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.poster-link{display:block;text-align:left;border:0;padding:0;border-radius:0}.poster-link img{display:block;width:100%;height:auto;border:1px solid var(--line)}.poster-link span{display:block;padding:10px 0;font-size:13px}.poster-link:hover{background:transparent}.poster-link:hover img{border-color:var(--green)}dialog{padding:16px;border:1px solid var(--line);border-radius:12px;max-width:96vw;width:1300px;max-height:95vh;background:var(--paper)}dialog::backdrop{background:#10281dde;backdrop-filter:blur(5px)}.dialog-tools{display:flex;justify-content:space-between;align-items:center;position:sticky;top:-16px;background:var(--paper);padding:8px 0;z-index:2}.dialog-tools a{color:var(--ink)}#poster-close{padding:0 16px}#poster-image{width:100%;height:auto;display:block}.module-note{font-size:12px;color:var(--muted)}
@media(max-width:720px){.module-nav{gap:3px;margin-bottom:16px}.module-nav button{padding:10px 5px;font-size:11px}.module-nav b{display:block;margin:0;font-size:11px}.compare-grid{grid-template-columns:1fr;gap:16px}.compare-pair{gap:14px}.compare-item img{height:330px}.poster-grid{grid-template-columns:1fr}.gallery{margin-top:32px}.gallery-title h2{font-size:18px}.install-steps{grid-template-columns:repeat(3,1fr)}#install-panel{display:block}.install-copy{min-height:80px}.frame-icon{width:12px;height:36px}.node-svg{height:240px}.stage{height:58vh}.gallery-title{align-items:baseline}.stage-label strong{font-size:12px}.light-badge{font-size:10px}.header-note{max-width:120px}.install-actions{margin-top:12px}}
'''
tabs='''<nav class="module-nav" aria-label="产品演示章节"><button data-module="1" class="selected" aria-pressed="true"><b>01</b>构造与挂件</button><button data-module="2" aria-pressed="false"><b>02</b>框型与灯光</button><button data-module="3" aria-pressed="false"><b>03</b>墙体安装</button></nav>'''
s=s.replace('__TABS__',tabs).replace('__CSS__',css).replace('<aside class="panel"','<aside id="config-panel" class="panel"',1)
install='''<aside id="install-panel" hidden><h2>800 × 2400 mm / 整板挂装</h2><div class="install-steps" role="group" aria-label="安装与拆卸步骤">'''
for i,n in enumerate(['分离待装','抬高板材','靠墙对位','下落扣合','上移脱扣','向外取下']):install+=f'<button data-step="{i}" data-requires-model disabled aria-pressed="{str(i==0).lower()}">{i+1:02} {n}</button>'
install+='''</div><div class="install-copy"><h3 id="install-title">01 · 分离待装</h3><p id="install-body">墙侧铝条与产品铝挂件分别固定，上下两道一一对应。</p></div><div class="install-actions"><button id="play-install" data-requires-model disabled aria-pressed="false">播放安装与拆卸</button><button id="install-prev" data-requires-model disabled>上一步</button><button id="install-next" data-requires-model disabled>下一步</button></div><svg class="node-svg" viewBox="0 0 450 600" role="img" aria-label="墙侧铝条与产品铝挂件正反 C 形扣口紧密咬合剖面"><rect x="22" y="25" width="57" height="560" fill="#d3d9cd"/><path d="M79 44 H137 V346 H199 V290 L210 251 H246 L257 290 V379 H79 Z" fill="#789180"/><path d="M140 215 H316 V559 H256 V535 H280 V400 L259 379 V245 H194 V300 L184 338 H151 L140 317 Z" fill="#4e5b59"/><rect x="316" y="28" width="28" height="546" fill="#354542"/><rect x="344" y="28" width="45" height="546" fill="#c8cfc5"/></svg><p class="node-label">墙侧铝条 / 产品铝挂件 · 正反扣口咬合</p><p class="note">墙体与板材顶部齐平。抬挂需留操作空间，顶部收口在挂装后完成；拆卸前恢复上移空间。动画位移为动作示意。</p></aside>'''
s=s.replace('</aside></div>', '</aside>'+install+'</div>',1)
content='<section id="comparison" hidden aria-label="三种框型亮灯熄灯对比"><div class="compare-grid">'
for i,(n,d) in enumerate([('全明框','四边明框'),('半隐框','上下明框 · 左右隐框'),('全隐框','正面无外露框')]):
 content+=f'<article class="compare-column"><h2>{n}</h2><p>{d} · 800 × 2400 mm</p><div class="compare-pair">'
 for st,en in [('熄灯','off'),('亮灯','on')]:content+=f'<button class="compare-item" data-compare="{i},{en}" aria-label="三维查看{n}{st}"><img src="assets/frame-{i}-{en}.png" alt="{n}{st}效果，800乘2400毫米" loading="lazy"><span>{st}</span></button>'
 content+='</div></article>'
content+='</div><p class="compare-hint">点击任意板材，进入对应的三维细节视图。框型、石纹及透光表现参考实拍样品。</p></section><section class="gallery"><div class="gallery-title"><h2>产品图册</h2><a href="assets/posters.zip" download>下载三张高清海报 ↗</a></div><div class="poster-grid">'
for i,n in enumerate(['构造、挂件与透光表现','框型样式比选','墙体安装示意'],1):content+=f'<button class="poster-link" data-poster="{i}" aria-label="放大查看{n}"><img src="assets/poster-0{i}.png" alt="{n}海报" loading="lazy"><span>0{i} / {n} ↗</span></button>'
content+='</div></section><dialog id="poster-dialog" aria-label="高清海报"><div class="dialog-tools"><a id="poster-original" target="_blank" rel="noopener">打开原尺寸图片 ↗</a><button id="poster-close">关闭</button></div><img id="poster-image" alt="产品海报"></dialog>'
s=s.replace('__CONTENT__',content).replace('<head>','<head><base href="./"><meta name="description" content="EYESHOT 颜界热熔天然石墙板系统：800×2400 mm 整板三维构造、框型亮灯对比与墙体挂装演示。"><meta name="release" content="800x2400-20260926">',1)
(p/'site/index.html').write_text(s)
a=(p/'app.js').read_text().replace('__EXTRA__',(p/'extra.js').read_text())
a=a.replace('const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;','const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;if(state.module===2)return;')
(p/'app.entry.js').write_text(a)
