import {scenes,variants} from './gallery-scenes.js';
const $=s=>document.querySelector(s),state={scene:0,reference:0,zoom:1,x:0,y:0,clean:false,variant:null};
const activeScene=()=>state.variant?.reference||scenes[state.scene];
const headlines=['让建筑，成为一束光。','走进一幅会发光的山水。','一面石，一整个光的世界。','把星空，藏进奢品的光里。','推开石纹，让空间流动。','每一次进入，都有仪式。','走进星空，让时间慢下来。','四片石纹，一幅完整的画。','把光，留在日常的方寸。','下一张图纸，从这里开始。'];
const sceneShort=['建筑外立面','景观庭院','整板墙面','奢品展廊','会客厅','礼宾玄关','星空影院','石纹餐厅','艺术盘','材料工坊'];
const points=[[72,42],[63,43],[74,42],[67,41],[68,39],[69,41],[68,40],[68,40],[63,55],[68,40]];
const scenePath=i=>`assets/campaign/scene-${String(i+1).padStart(2,'0')}.jpg`;
let generation=0,heroFade;
function fitHeadline(){const h=$('#headline');h.style.fontSize='';const available=h.clientWidth,needed=h.scrollWidth;if(needed>available){h.style.fontSize=Math.max(15,parseFloat(getComputedStyle(h).fontSize)*available/needed*.985)+'px';}}
new ResizeObserver(fitHeadline).observe($('.caption'));
async function showImage(im,alt){heroFade?.cancel();const old=$('#hero');if(old.src&&old.src!==im.src){$('#hero-previous').src=old.src;$('#hero-previous').hidden=false;$('#hero-previous').style.transform=old.style.transform;old.src=im.src;heroFade=old.animate([{opacity:0},{opacity:1}],{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:900,easing:'cubic-bezier(.2,.65,.3,1)',fill:'both'});heroFade.finished.then(()=>$('#hero-previous').hidden=true).catch(()=>{});}else old.src=im.src;old.alt=alt;}
function reference(){const s=activeScene(),c=s.cases[state.reference];const official=s.website||{title:s.product,section:s.product,image:c.image,url:s.source};$('#teaser-img').src=official.image;$('#teaser-img').alt=official.title;$('#teaser-kind').textContent='官网对应页面';$('#teaser-title').textContent=official.title;$('#teaser-open').href=official.url;$('#reference-kind').textContent=c.kind;$('#reference-img').src=c.image;$('#reference-img').alt=c.title;$('#reference').href=c.url;$('#reference-title').textContent=c.title;$('#reference-relation').textContent=c.relation;$('#ref-count').textContent=`${state.reference+1} / ${s.cases.length}`;}
function transform(){const r=$('#gallery').getBoundingClientRect(),maxX=r.width*(state.zoom-1)/2,maxY=r.height*(state.zoom-1)/2;state.x=Math.max(-maxX,Math.min(maxX,state.x));state.y=Math.max(-maxY,Math.min(maxY,state.y));$('#hero').style.transform=`translate(${state.x}px,${state.y}px) scale(${state.zoom})`;$('#zoom-value').textContent=`${Math.round(state.zoom*100)}%`;$('#hero').style.cursor=state.zoom>1?'grab':'default';}
async function go(i){const job=++generation,stateScene=scenes[i];state.scene=i;state.variant=null;state.reference=0;state.zoom=1;state.x=state.y=0;transform();
 $('#door-variants').hidden=![4,5].includes(i);$('#case-teaser').hidden=false;document.dispatchEvent(new CustomEvent('museum-scene',{detail:i})); $('#number').textContent=String(i+1).padStart(2,'0');$('#detail-number').textContent=`${String(i+1).padStart(2,'0')} / 10 · ${stateScene.room}`;$('#english').textContent=stateScene.en;$('#detail-en').textContent=stateScene.en;$('#headline').textContent=headlines[i];fitHeadline();$('#tagline').textContent=stateScene.point;$('#location').textContent=`EYESHOT / ${stateScene.room}`;$('#hotspot-label').textContent=stateScene.product;$('#product-hotspot').style.left=points[i][0]+'%';$('#product-hotspot').style.top=points[i][1]+'%';$('#product').textContent=stateScene.product;$('#point').textContent=stateScene.point;$('#description').textContent=stateScene.description.replace('这里先验证参观逻辑和开启动作；门片与五金细节将在正式建模阶段按产品资料落实。','门片与五金按具体产品配置深化。').replace('虚拟场景展示使用关系；正式模型的轴位、缝隙和五金按实物深化。','轴位、缝隙和五金以实物及深化资料为准。');$('#features').replaceChildren(...stateScene.features.map((v,n)=>{const p=document.createElement('p'),span=document.createElement('span');span.textContent=String(n+1).padStart(2,'0');p.append(span,document.createTextNode(v));return p;}));$('#product-action').textContent=[2,9].includes(i)?'进入构造 · 框型 · 安装演示':'查看产品与应用资料';$('#product-source').href=stateScene.source;reference();
 $('#download').href=`assets/campaign/scene-${String(i+1).padStart(2,'0')}.png`;$('#download').download=`EYESHOT-材料艺术馆-${String(i+1).padStart(2,'0')}-${sceneShort[i]}.png`;
 document.querySelectorAll('[data-scene]').forEach(b=>{const selected=+b.dataset.scene===i;b.classList.toggle('active',selected);b.setAttribute('aria-current',selected?'step':'false');});document.querySelector(`#scenes [data-scene="${i}"]`)?.scrollIntoView({block:'nearest',inline:'nearest'});history.replaceState(null,'',`#scene-${i+1}`);$('#status').textContent=`${stateScene.room}：${stateScene.product}`;
 $('#picture-loading').hidden=false;const im=new Image();im.src=scenePath(i);try{await im.decode();if(job!==generation)return;await showImage(im,`EYESHOT 材料艺术馆 · ${stateScene.room}，虚拟应用概念`);$('#hero').dataset.scene=i;$('#hero').dataset.loaded='true';$('#picture-loading').hidden=true;}catch{if(job!==generation)return;$('#picture-loading').textContent='此场景正在准备，请稍后刷新。';$('#hero').dataset.loaded='false';}
 const next=new Image();next.src=scenePath((i+1)%10);
}
function details(){if(!$('#details-dialog').open)$('#details-dialog').showModal();}
for(const v of variants){const b=document.createElement('button');b.textContent=v.name;b.onclick=async()=>{const im=new Image();im.src=`assets/campaign/${v.path}.jpg`;await im.decode();state.variant=v;state.reference=0;await showImage(im,`${v.name} · 虚拟应用概念`);$('#headline').textContent=v.reference.title;fitHeadline();$('#tagline').textContent=v.reference.point;$('#point').textContent=v.reference.point;$('#features').replaceChildren(...v.reference.features.map(t=>{const p=document.createElement('p');p.textContent=t;return p;}));reference();$('#hotspot-label').textContent=v.name;$('#download').href=`assets/campaign/${v.path}.png`;$('#download').download=`EYESHOT-${v.name}.png`;$('#product').textContent=v.reference.product;$('#description').textContent=v.reference.description;$('#product-source').href=v.reference.source;};$('#door-variants').append(b);} for(const [i,s] of scenes.entries()){const b=document.createElement('button');b.dataset.scene=i;const n=document.createElement('span');n.textContent=String(i+1).padStart(2,'0');b.append(n,document.createTextNode(sceneShort[i]));b.onclick=()=>go(i);$('#scenes').append(b);const c=document.createElement('button');c.dataset.scene=i;const image=document.createElement('img');image.src=scenePath(i);image.alt=s.room;image.loading='lazy';const number=document.createElement('span');number.textContent=String(i+1).padStart(2,'0')+' / '+s.en;const title=document.createElement('b');title.textContent=s.room;const text=document.createElement('p');text.textContent=s.product;c.append(image,number,title,text);c.onclick=()=>{$('#route-dialog').close();go(i);};$('#route-cards').append(c);}
$('#details-open').onclick=details;$('#product-hotspot').onclick=details;$('#details-close').onclick=()=>$('#details-dialog').close();$('#teaser-close').onclick=()=>{$('#case-teaser').hidden=true;};$('#tour-map').onclick=()=>$('#route-dialog').showModal();$('#route-close').onclick=()=>$('#route-dialog').close();$('#back').onclick=()=>go((state.scene+9)%10);$('#forward').onclick=()=>go((state.scene+1)%10);$('#ref-back').onclick=()=>{state.reference=(state.reference+activeScene().cases.length-1)%activeScene().cases.length;reference();};$('#ref-forward').onclick=()=>{state.reference=(state.reference+1)%activeScene().cases.length;reference();};
function clean(on){state.clean=on;document.body.classList.toggle('clean',on);$('#clean-return').hidden=!on;}$('#clean').onclick=()=>clean(true);$('#clean-return').onclick=()=>clean(false);$('#zoom-in').onclick=()=>{state.zoom=Math.min(2.4,state.zoom+.2);transform();};$('#zoom-out').onclick=()=>{state.zoom=Math.max(1,state.zoom-.2);transform();};$('#zoom-reset').onclick=()=>{state.zoom=1;state.x=state.y=0;transform();};
$('#product-action').onclick=()=>{if([2,9].includes(state.scene)){if(!$('#product-frame').src)$('#product-frame').src='https://www.eyeshot.art/products/stone-panel-system/index.html';$('#product-dialog').showModal();}else window.open(activeScene().source,'_blank','noopener');};$('#product-close').onclick=()=>$('#product-dialog').close();
let drag;$('#hero').addEventListener('pointerdown',e=>{if(state.zoom<=1)return;drag={x:e.clientX,y:e.clientY,bx:state.x,by:state.y};$('#hero').setPointerCapture(e.pointerId);});$('#hero').addEventListener('pointermove',e=>{if(!drag)return;state.x=drag.bx+e.clientX-drag.x;state.y=drag.by+e.clientY-drag.y;transform();});$('#hero').addEventListener('pointerup',()=>drag=null);$('#hero').addEventListener('pointercancel',()=>drag=null);document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='ArrowRight')go((state.scene+1)%10);if(e.key==='ArrowLeft')go((state.scene+9)%10);if(e.key==='Escape')clean(false);});
const initial=location.hash.match(/^#scene-(\d+)$/);go(initial&&+initial[1]>0&&+initial[1]<=10?+initial[1]-1:0);
