import * as THREE from 'three';
import {GLTFLoader} from './assets/loaders/GLTFLoader.js';
import {OrbitControls} from './assets/OrbitControls.js';
import {RoomEnvironment} from './assets/environments/RoomEnvironment.js';
import {EffectComposer} from './assets/postprocessing/EffectComposer.js';
import {RenderPass} from './assets/postprocessing/RenderPass.js';
import {SSAOPass} from './assets/postprocessing/SSAOPass.js';
import {UnrealBloomPass} from './assets/postprocessing/UnrealBloomPass.js';
import {OutputPass} from './assets/postprocessing/OutputPass.js';
import {scenes} from './gallery-scenes.js';
const $=s=>document.querySelector(s),dialog=$('#model-dialog');
const modelRoot=dialog.dataset.modelRoot||'assets/museum',modelFile=dialog.dataset.modelFile||'museum.glb',modelVersion=dialog.dataset.modelVersion||'current';
const asset=name=>`${modelRoot}/${name}?v=${encodeURIComponent(modelVersion)}`;
let tourStops=[];let composer;let renderer,world,camera,controls,building,bookmarks,ready=false,booting,selected=0,motion,tour,roofs=[],markers=[];
let tourDuration=100000,tourPaused=0,tourVisited=[],tourFraction=0;
let roofVisible=true,last=0,pivot,barn,pivotBase=0,barnBase=0,barnTravel=1.35,doorOpen=false,doorMix=0;
const v=a=>new THREE.Vector3(...a);
function flight(eye,target,duration=1800){$('#model-canvas').dataset.settled='false';motion={start:performance.now(),duration,from:camera.position.clone(),to:v(eye),fromTarget:controls.target.clone(),toTarget:v(target)};}
function focus(i){selected=i;stopTour();$('#model-tour').textContent='播放路线';if(!ready)return;const c=bookmarks[i];camera.fov=c.fov;camera.updateProjectionMatrix();flight(c.eye,c.target);mark();}
function mark(){document.querySelectorAll('#model-route button').forEach((b,i)=>b.classList.toggle('active',i===selected));$('#model-canvas').dataset.scene=selected;}
function overview(){stopTour();roofs.forEach(o=>o.visible=false);roofVisible=false;renderer.shadowMap.needsUpdate=true;markers.forEach(o=>o.visible=true);camera.fov=52;camera.updateProjectionMatrix();flight([29,27,35],[0,0,0]);}
function stopTour(){tour=null;tourPaused=0;tourFraction=0;$('#model-tour').textContent='播放路线';}
function play(){
 if(tour){tourPaused=performance.now()-tour.start;tour=null;$('#model-tour').textContent='继续漫游';return;}
 roofs.forEach(o=>o.visible=true);roofVisible=true;renderer.shadowMap.needsUpdate=true;markers.forEach(o=>o.visible=false);
 controls.minDistance=.5;camera.fov=73;camera.updateProjectionMatrix();
 if(!tourPaused){tourVisited=[];tourFraction=0;selected=0;mark();tourVisited.push(0);}
 tour={start:performance.now()-tourPaused,duration:tourDuration};motion=null;$('#model-tour').textContent='暂停漫游';
}
async function boot(){if(ready)return;if(booting)return booting;booting=(async()=>{try{
 renderer=new THREE.WebGLRenderer({canvas:$('#model-canvas'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.88;world=new THREE.Scene();world.background=new THREE.Color(0xc7cdc0);world.fog=new THREE.Fog(0xc7cdc0,50,130);camera=new THREE.PerspectiveCamera(61,1,.05,180);camera.position.set(22,9,31);controls=new OrbitControls(camera,$('#model-canvas'));controls.enableDamping=true;controls.minDistance=.3;controls.maxDistance=100;controls.maxPolarAngle=Math.PI*.53;controls.target.set(0,1.8,12);controls.addEventListener('start',()=>{motion=null;stopTour();});
 const pmrem=new THREE.PMREMGenerator(renderer);world.environmentIntensity=.5;world.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;pmrem.dispose();
 world.add(new THREE.HemisphereLight(0xffedcf,0x65775f,.6));const sun=new THREE.DirectionalLight(0xffe4b0,3.8);sun.position.set(-18,30,24);sun.castShadow=true;sun.shadow.mapSize.set(innerWidth>760?2048:1024,innerWidth>760?2048:1024);Object.assign(sun.shadow.camera,{left:-25,right:25,top:30,bottom:-30,near:1,far:100});sun.shadow.bias=-.001;world.add(sun);
 const readJson=async name=>{const r=await fetch(asset(name),{cache:'no-store'});if(!r.ok)throw Error(name);return r.json();};
 const [gltf,data,tourData]=await Promise.all([new GLTFLoader().loadAsync(asset(modelFile)),readJson('cameras.json'),readJson('tour.json')]);
 building=gltf.scene;world.add(building);bookmarks=data.cameras;
 if(tourData.revision!==modelVersion)throw Error('Model and tour revision mismatch');
 tourStops=tourData.stops.map(s=>s.scene===null?s:{...bookmarks[s.scene],scene:s.scene});tourDuration=tourData.duration_ms;
 if(bookmarks.length!==10||tourStops.filter(s=>s.scene!==null).length!==10)throw Error('Ten scene route required');
 $('#model-canvas').dataset.version=modelVersion;
 $('#model-canvas').dataset.modelSha256=tourData.model_sha256;
 building.traverse(o=>{if(o.name.startsWith('Roof'))roofs.push(o);if(o.name==='Pivot_stone_door'){pivot=o;pivotBase=o.rotation.y;}if(o.name==='Barn_moving_stone_door'){barn=o;barnBase=o.position.x;barnTravel=o.userData.travel_m??1.35;}if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material.name==='Clear glazing'){o.material=new THREE.MeshStandardMaterial({color:0xcbd8c7,roughness:.15,metalness:.1,transparent:true,opacity:.1,depthWrite:false});o.castShadow=false;}}});
 for(const c of bookmarks){const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const x=canvas.getContext('2d');x.fillStyle='#f5efdb';x.beginPath();x.arc(64,64,46,0,Math.PI*2);x.fill();x.fillStyle='#254035';x.font='38px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(String(c.id+1).padStart(2,'0'),64,64);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),depthTest:false}));sprite.position.copy(v(c.eye));sprite.position.y=4.7;sprite.scale.set(1.1,1.1,1);sprite.userData.id=c.id;sprite.renderOrder=3;sprite.visible=false;world.add(sprite);markers.push(sprite);}
 for(const x of [-10,10])for(const z of [-8,0,8]){const lamp=new THREE.PointLight(0xffce86,18,12,2);lamp.position.set(x,3.2,z);world.add(lamp);}
 if(innerWidth>760){composer=new EffectComposer(renderer);composer.addPass(new RenderPass(world,camera));const ao=new SSAOPass(world,camera,1,1);ao.kernelRadius=.3;ao.minDistance=.003;ao.maxDistance=.15;composer.addPass(ao);composer.addPass(new UnrealBloomPass(new THREE.Vector2(1,1),.15,.35,1.05));composer.addPass(new OutputPass());}
 function size(){const r=$('#model-stage').getBoundingClientRect();if(r.width&&r.height){renderer.setSize(r.width,r.height,false);if(composer)composer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}}new ResizeObserver(size).observe($('#model-stage'));size();renderer.shadowMap.needsUpdate=true;ready=true;$('#model-loading').hidden=true;$('#model-canvas').dataset.ready='true';$('#model-canvas').dataset.model=modelFile;focus(selected);
 let down;$('#model-canvas').addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);$('#model-canvas').addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=$('#model-canvas').getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(markers.filter(s=>s.visible))[0];if(hit){markers.forEach(s=>s.visible=false);roofs.forEach(s=>s.visible=true);roofVisible=true;focus(hit.object.userData.id);}});
 renderer.setAnimationLoop(now=>{if(!dialog.open)return;const dt=Math.min(.06,(now-(last||now))/1000);last=now;if(tour){const t=Math.min(1,(now-tour.start)/tour.duration);tourFraction=t;const position=t*(tourStops.length-1),n=Math.min(tourStops.length-2,Math.floor(position)),fraction=position-n,progress=Math.min(1,fraction/.82),ease=progress*progress*(3-2*progress),a=tourStops[n],b=tourStops[n+1];camera.position.lerpVectors(v(a.eye),v(b.eye),ease);controls.target.lerpVectors(v(a.target),v(b.target),ease);if(b.scene!==null&&progress===1){selected=b.scene;if(!tourVisited.includes(selected))tourVisited.push(selected);mark();}if(t>=1){tour=null;tourPaused=0;$('#model-tour').textContent='重新漫游';}}else if(motion){const t=Math.min(1,(now-motion.start)/motion.duration),e=t*t*(3-2*t);camera.position.lerpVectors(motion.from,motion.to,e);controls.target.lerpVectors(motion.fromTarget,motion.toTarget,e);if(t===1)motion=null;}if(Math.abs(doorMix-(doorOpen?1:0))>.001)renderer.shadowMap.needsUpdate=true;doorMix=THREE.MathUtils.damp(doorMix,doorOpen?1:0,4,dt);if(pivot)pivot.rotation.y=pivotBase-doorMix*.8;if(barn)barn.position.x=barnBase+doorMix*barnTravel;if(tour||tourPaused||tourFraction===1){$('.model-tip').textContent=`连续漫游 · ${String(selected+1).padStart(2,'0')} ${scenes[selected].room} · ${Math.round(tourFraction*100)}%${tourPaused&&!tour?' · 已暂停':''}`;}else{$('.model-tip').textContent='拖动观察 · 双指缩放 · 十个机位共享同一建筑';}controls.update();if(composer)composer.render();else renderer.render(world,camera);$('#model-canvas').dataset.settled=String(!motion&&!tour);$('#model-canvas').dataset.audit=JSON.stringify({sameModel:true,version:modelVersion,scene:selected,tourProgress:+tourFraction.toFixed(4),visited:tourVisited,paused:tourPaused>0&&!tour,cameras:bookmarks.length,hasPivot:!!pivot,hasBarn:!!barn,barnTravel,meshCalls:renderer.info.render.calls,walking:!!tour,roof:roofVisible,camera:camera.position.toArray().map(n=>+n.toFixed(2)),doorProgress:+doorMix.toFixed(2)});});
 }catch(e){console.error(e);$('#model-loading').textContent='三维空间未能载入，请使用支持 WebGL 的浏览器重试。';booting=null;}})();return booting;}
for(const [i,s] of scenes.entries()){const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0')+' '+s.room;b.onclick=()=>{roofs.forEach(o=>o.visible=true);roofVisible=true;renderer.shadowMap.needsUpdate=true;markers.forEach(o=>o.visible=false);focus(i);};$('#model-route').append(b);}
async function open(walk=false){stopTour();selected=Number(document.querySelector('#number').textContent)-1;dialog.showModal();await boot();if(!ready)return;if(walk){camera.position.copy(v(bookmarks[0].eye));controls.target.copy(v(bookmarks[0].target));controls.update();doorOpen=true;play();}else overview();}
$('#model-open').onclick=()=>open();$('#walk-open').onclick=()=>open(true);$('#model-close').onclick=()=>{stopTour();dialog.close();};dialog.addEventListener('close',stopTour);$('#model-overview').onclick=overview;$('#model-roof').onclick=()=>{roofVisible=!roofVisible;renderer.shadowMap.needsUpdate=true;roofs.forEach(o=>o.visible=roofVisible);};$('#model-tour').onclick=play;$('#model-reset').onclick=()=>focus(selected);document.addEventListener('museum-scene',e=>{selected=e.detail;if(ready)focus(selected);});
const doorButton=document.createElement('button');doorButton.textContent='门片开合';doorButton.onclick=()=>{doorOpen=!doorOpen;};$('.model-controls').append(doorButton);
