const base='https://www.eyeshot.art/';
const project=(slug,title,relation='同材质案例参考')=>({title,kind:'官网项目实景',relation,image:`assets/${slug}-1.jpg`,url:base+`projects/${slug}/index.html`});
const application=(file,title)=>({title,kind:'官网应用素材',relation:'用于说明应用方向，不作为已建项目证明',image:`assets/${file}.jpg`,url:base+'products/barn-door-pro/index.html'});
export const scenes=[
 {id:0,title:'光的建筑表皮',en:'THE FACADE',room:'建筑外立面',product:'热熔天然石幕墙',tag:'建筑尺度',point:'天然石纹，成为建筑的第一张面孔。',description:'把石材、玻璃与光组织成完整的建筑表皮。白天看天然纹理，亮灯时看透光层次；侧边可对照真实幕墙项目。',features:['立面分格与纹理排布','自然光 / 透光两种表情','收口、检修与工程深化'],source:base+'solutions/facade/index.html',cases:[project('the-reserve-sg','新加坡 The Reserve','对应应用：幕墙工程'),project('luxury-flagship','高奢品牌旗舰店','对应应用：天然黑白根立面'),project('wuxi-sunshine','无锡阳光城','对应应用：透光幕墙')],action:'查看夜间立面',type:'facade'},
 {id:1,title:'可行走的石纹画卷',en:'THE COURTYARD',room:'景观庭院',product:'景观展墙',tag:'路径与光',point:'让材料把归家路径，串成一段风景。',description:'用连续展墙组织路径与视线，把天然石纹变成庭院中的长幅画面。景观灯光与材料共同塑造晨昏体验。',features:['连续展墙与转角关系','路径、视线与入口组织','夜间透光景观'],source:base+'solutions/landscape/index.html',cases:[project('poly-yuncheng','杭州保利云城','对应应用：景观展墙'),project('wenzhou-outang','温州瓯塘寻梦','对应应用：院落展卷'),project('vanke-langshi','合肥万科朗拾','对应应用：发光入口')],action:'切换透光',type:'landscape'},
 {id:2,title:'一块整板，一面光',en:'THE WALL SYSTEM',room:'整板墙面展厅',product:'热熔天然石墙板系统',tag:'800 × 2400 mm',point:'从正面石纹，到背面的挂接细节。',description:'以确认过的 800 × 2400 mm 整板为展示基准。对比框型、灯光与复合层级，再进入独立产品页查看 C 形铝挂件和抬高挂装方式。',features:['全明框 / 半隐框 / 全隐框','熄灯自然纹理 / 亮灯透光','产品铝挂件与可拆卸安装'],source:base+'products/stone-panel-system/index.html',cases:[project('shenzhen-taiziwan','深圳招商太子湾','同材质厅堂与吊顶参考，非此墙板型号实装证明'),project('crland-hangzhou','杭州华润元起观潮','同材质空间参考，非此墙板型号实装证明')],action:'展开构造与安装',type:'wall'},
 {id:3,title:'石纹轻移，空间相连',en:'BARN DOOR PLUS',room:'会客厅',product:'谷仓门 Plus',tag:'轨道移门',point:'开合之间，门片成为一幅移动的画。',description:'以会客厅为背景，展示谷仓门的外露轨道与横向开合。这里先验证参观逻辑和开启动作；门片与五金细节将在正式建模阶段按产品资料落实。',features:['外露轨道横向开合','门片与墙面纹理协调','会客与生活空间连接'],source:base+'products/barn-door-pro/index.html',cases:[application('barn-door-plus-cover','谷仓门 Plus 应用'),project('luxury-flagship','高奢品牌旗舰店','同材质立面参考，非谷仓门实装案例')],action:'演示开合',type:'barn'},
 {id:4,title:'进入空间的仪式',en:'THE PIVOT DOOR',room:'礼宾玄关',product:'旋转门',tag:'偏轴开启',point:'门，成为进入空间前的第一道光。',description:'在礼宾玄关演示偏轴开启的透光门片。观察关闭时的完整画面与打开时的通行关系，避免只展示一张静态效果图。',features:['中轴 / 偏轴方案','整片石纹与开启关系','入口与会所接待'],source:base+'products/barn-door-pro/index.html',cases:[application('pivot-door-01','旋转门应用'),project('crland-beijing','北京华润中环悦府','同材质归家空间参考，非旋转门实装案例')],action:'演示开合',type:'pivot'},
 {id:5,title:'一扇门，也是一面画',en:'THE HINGED DOOR',room:'书房',product:'平开门',tag:'明确空间边界',point:'关闭时完整，开启时轻盈。',description:'用书房场景说明平开门的门洞、边框与开合关系。侧边展示官网应用素材；同门型的真实项目案例后续补入。',features:['合页开启与门洞关系','门片、边框与墙面协调','书房 / 卧室 / 衣帽间'],source:base+'products/barn-door-pro/index.html',cases:[application('hinged-door-01','平开门应用'),application('hinged-door-02','平开门局部'),project('crland-hangzhou','杭州华润元起观潮','同材质空间参考，非平开门实装案例')],action:'演示开合',type:'hinged'},
 {id:6,title:'沿着光，打开空间',en:'THE SLIDING DOOR',room:'长廊与套房',product:'平移门',tag:'连续界面',point:'用横向移动，释放空间的尺度。',description:'在长廊端部演示双扇平移。门、墙面与光感共同形成连续界面，区别于谷仓门展区的外露轨道做法。',features:['双扇横向开合示意','连续透光界面','走廊 / 套房 / 开放厅区'],source:base+'products/barn-door-pro/index.html',cases:[application('sliding-door-01','平移门应用'),application('sliding-door-02','平移门细节'),project('crland-chengdu','成都华润高新天序','同材质入口参考，非平移门实装案例')],action:'演示开合',type:'sliding'},
 {id:7,title:'一面屏风，多种尺度',en:'THE FOLDING DOOR',room:'多功能沙龙',product:'折叠门',tag:'大面宽开合',point:'展开是一幅画，收起是一处开放空间。',description:'通过双侧折叠动作说明空间如何从分隔转为连通。虚拟场景展示使用关系；正式模型的轴位、缝隙和五金按实物深化。',features:['多扇折叠与收纳','展开形成连续屏风','开放与分隔两种状态'],source:base+'products/barn-door-pro/index.html',cases:[application('folding-door-01','折叠门应用'),application('folding-door-02','折叠门组合'),project('wenzhou-outang','温州瓯塘寻梦','同材质展墙参考，非折叠门实装案例')],action:'演示开合',type:'folding'},
 {id:8,title:'方寸之间，光有温度',en:'THE ART OBJECT',room:'茶室与艺术陈设',product:'天然光感艺术盘',tag:'从建筑到器物',point:'把亿万年的石纹，放到日常触手可及处。',description:'在茶席中展示艺术盘，连接材料、氛围照明与陈设。可由案头延展至墙面艺术装置；器物尺寸及边缘构造以实物核对为准。',features:['茶具平台与案头陈设','氛围照明与触控','墙面艺术应用'],source:base+'products/art-tray/index.html',cases:[{title:'天然光感艺术盘',kind:'官网产品素材',relation:'产品应用素材，已建项目案例待补',image:'assets/art-tray-01.jpg',url:base+'products/art-tray/index.html'},{title:'艺术盘应用细节',kind:'官网产品素材',relation:'以实物与产品手册为深化依据',image:'assets/art-tray-02.jpg',url:base+'products/art-tray/index.html'}],action:'切换透光',type:'tray'},
 {id:9,title:'把材料带进下一张图纸',en:'THE MATERIAL LIBRARY',room:'材料与构造工坊',product:'材料选型与系统深化',tag:'选材 → 构造 → 项目',point:'看完空间，再看清它如何成为现实。',description:'八大纹理系列集中选型；由复合层、框型、挂接和维护进入深化。产品、解决方案、真实案例与下载资料在此汇合。',features:['八大天然石纹理系列','墙板复合层与连接节点','手册、案例与项目咨询'],source:base+'material/index.html',cases:[project('the-reserve-sg','新加坡 The Reserve','材料的幕墙尺度应用'),project('poly-yuncheng','杭州保利云城','材料的景观尺度应用')],action:'进入构造演示',type:'library'},
];
export const materials=['巴西白玉','毕加索','云白玉','山水云','黑洞石','鱼肚白','雪花白','金兰玉'];
